# @package _group_
name: GLDv2Dataset
kwargs:
  data_dir: ${env:HOME}/projects/made/landmarks-recognition/data/train10k
  csv_path: ${env:HOME}/projects/made/landmarks-recognition/data/train10k.csv
  test_size: 0.2

sampler:
  name: MPerClassSampler
  kwargs:
    batch_size: 128
    samples_per_class: 4
