version: '3'
services:
  flask:
    container_name: landmarks-search
    build: .
    command: poetry run streamlit run landmarks_app.py
    ports:
      - "5234:8501"
    volumes:
      - ./:/landmarks_app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
              - gpu
              - utility # nvidia-smi
              - compute # CUDA. Required to avoid "CUDA version: N/A"
