defaults:
  - experience: default

  - dataset: gldv2_10k

  - loss: roadmap

  - memory: default

  - model: deit

  - optimizer: gldv2_deit

  - transform: gldv2

  - hydra/job_logging: colorlog

  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ${experience.log_dir}/${experience.experiment_name}/outputs

  sweep:
    dir: ${experience.log_dir}
    subdir: ${experience.experiment_name}/outputs
