# @package _group_
name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: cgd
  embed_dim: 512
  norm_features: False
  without_fc: False
  with_autocast: True
