PYTHONPATH=${HOME}/projects/made/landmarks-recognition/andrey-research-repo python retrieval/single_experiment_runner.py \
  'experience.experiment_name=GLDv2_ROADMAP_classification_splits_resnet_v2_${dataset.sampler.kwargs.batch_size}' \
  'experience.log_dir=${env:HOME}/projects/made/landmarks-recognition/andrey-research-repo/experiments/ROADMAP' \
  experience.seed=42 \
  experience.max_iter=1000 \
  optimizer=gldv2_deit \
  model=resnet \
  transform=gldv2 \
  dataset=gldv2_10k_classification_splits \
  dataset.sampler.kwargs.batch_size=440 \
  loss=roadmap
