PYTHONPATH=${HOME}/projects/made/landmarks-recognition/andrey-research-repo python retrieval/single_experiment_runner.py \
  'experience.experiment_name=GLDv2_ROADMAP_CGD_${dataset.sampler.kwargs.batch_size}' \
  'experience.log_dir=${env:HOME}/projects/made/landmarks-recognition/andrey-research-repo/experiments/ROADMAP' \
  experience.seed=42 \
  experience.max_iter=150 \
  optimizer=cub \
  model=cgd \
  transform=gldv2 \
  dataset=gldv2_10k \
  dataset.sampler.kwargs.batch_size=128 \
  loss=roadmap
